import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Cabeza from "./components/cabezera";
import Pie from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Knowy",
  description: "Generated by create next app",
  openGraph: {
    title: "Knowy Courses",
    description: "Portal de compra y venta de cursos"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/lupa.png"></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Cabeza />
        {children}
      <Pie />
      </body>
    </html>
  );
}
