import "./globals.css";
import Cabeza from "./components/cabezera";
// import Pie from "./components/piecera";
import AlterNav from "./components/cabezera";

export const metadata = {
  title: "Knowy",
  description: "Generated by create next app",
  openGraph: {
    title: "Knowy Courses",
    description: "Portal de compra y venta de cursos",
    image: "/pet.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/lupa.png"></link>
      </head>
      <body>
        <AlterNav />
        
        {children}

      </body>
    </html>
  );
}
